[project]
name = "brain-games"
version = "0.1.0"
description = "Brain Games"
authors = [{name = "Your Name"}]
readme = "README.md"
dependencies = [
    "prompt",
]

[project.scripts]
brain-games = "brain_games.scripts.brain_games:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
